export default {
  electoralDistrict: "선거구",
  affiliatedCommittee: "소속 위원회",
  electionCount: "당선 횟수",
  officePhone: "사무실 전화",
  officeRoom: "사무실 호실",
  memberHomepage: "의원 홈페이지",
  individualHomepage: "개별 홈페이지",
  email: "이메일",
  aide: "보좌관",
  chiefOfStaff: "선임 비서관",
  secretary: "비서관",
  officeGuide: "의원실 안내",
  history: "주요 약력",
} as const;
